export const MAJORS_BY_SCHOOL: Record<string, string[]> = {
  CAS: [
    "Africana Studies, BA",
    "Ancient History, BA",
    "Anthropology, BA",
    "Architecture, BA",
    "Biochemistry, BA",
    "Biology, BA",
    "Biophysics, BA",
    "Chemistry, BA",
    "Cinema and Media Studies, BA",
    "Classical Studies, BA",
    "Cognitive Science, BA",
    "Communication, BA",
    "Comparative Literature, BA",
    "Criminology, BA",
    "Design, BA",
    "Earth and Environmental Science, BA",
    "East Asian Languages and Civilizations, BA",
    "Economics, BA",
    "English, BA",
    "Environmental Studies, BA",
    "Fine Arts, BA",
    "Francophone, Italian and Germanic Studies, BA",
    "Gender, Sexuality, & Women's Studies, BA",
    "Health and Societies, BA",
    "Hispanic Studies, BA",
    "History, BA",
    "History of Art, BA",
    "Individualized Major, BA",
    "International Relations, BA",
    "International Studies, BA",
    "Jewish Studies, BA",
    "Latin American & Latinx Studies, BA",
    "Law and Society, BA",
    "Linguistics, BA",
    "Logic, Information, & Computation, BA",
    "Mathematical Economics, BA",
    "Mathematics, BA",
    "Middle Eastern Languages & Cultures, BA",
    "Modern Middle Eastern Studies, BA",
    "Music, BA",
    "Neuroscience, BA",
    "Nutrition Science, BA",
    "Philosophy, BA",
    "Philosophy, Politics and Economics, BA",
    "Physics, BA",
    "Political Science, BA",
    "Psychology, BA",
    "Religious Studies, BA",
    "Russian and East European Studies, BA",
    "Science, Technology and Society, BA",
    "Sociology, BA",
    "South Asia Studies, BA",
    "Theatre Arts, BA",
    "Urban Studies, BA",
    "Visual Studies, BA",
  ],
  SEAS: [
    "Artificial Intelligence, BSE",
    "Bioengineering, BSE",
    "Biomedical Science, BAS",
    "Chemical and Biomolecular Engineering, BSE",
    "Computer Engineering, BSE",
    "Computer Science, BAS",
    "Computer Science, BSE",
    "Digital Media Design, BSE",
    "Electrical Engineering, BSE",
    "Materials Science and Engineering, BSE",
    "Mechanical Engineering and Applied Mechanics, BSE",
    "Visual and Interactive Computing, BSE",
  ],
  Nursing: [
    "Nursing, BSN",
    "Nutrition Science, BSN",
  ],
  Wharton: [
    "Accounting, BS",
    "Artificial Intelligence for Business, BS",
    "Behavioral Economics, BS",
    "Business Analytics, BS",
    "Business Economics and Public Policy, BS",
    "Entrepreneurship and Innovation, BS",
    "Finance, BS",
    "Health Care Management and Policy, BS",
    "Impact, Value and Sustainable Business, BS",
    "Individualized, BS",
    "Leading Across Differences, BS",
    "Legal Studies & Business Ethics, BS",
    "Management, BS",
    "Marketing, BS",
    "Marketing & Communication, BS",
    "Marketing & Operations Management, BS",
    "Operations, Information & Decisions, BS",
    "Real Estate, BS",
    "Retailing, BS",
    "Statistics and Data Science, BS",
  ],
};

export function getMajorsForSchools(schools: string[]): string[] {
  if (!schools.length) {
    return Object.values(MAJORS_BY_SCHOOL).flat().sort();
  }
  const majors = new Set<string>();
  for (const school of schools) {
    for (const major of MAJORS_BY_SCHOOL[school] ?? []) {
      majors.add(major);
    }
  }
  return [...majors].sort();
}
